### ISSUE TITLE
Practical2_Chong

### ISSUE THREAD

**Issue by Chong03** [PU-SDS/git-and-github-training#5]
![image](https://user-images.githubusercontent.com/51225708/79189037-47c99500-7e53-11ea-8c93-6836b2180d23.png)
![image](https://user-images.githubusercontent.com/51225708/79189083-734c7f80-7e53-11ea-9c1c-072128393a0a.png)
![image](https://user-images.githubusercontent.com/51225708/79189139-8fe8b780-7e53-11ea-8a72-e6aafa38532f.png)

**Comment by farhansj** [comment]
good
